### ISSUE TITLE
SurrealDB 2 functions are not allowed

### ISSUE THREAD

**Issue by zvictor** [sebastianwessel/surrealdb-client-generator#64]
SurrealDB 2 has new functions that did not exist before.

When running surrealdb-client-generator in a code with such functions, it fails. As an example, `record::id` causes an error to be thrown.

> Record functions before SurrealDB 2.0 were located inside the module [meta](https://surrealdb.com/docs/surrealql/functions/database/meta). As of version 2.0, these functions are now part of SurrealDB's [record](https://surrealdb.com/docs/surrealql/functions/database/record) functions.

```haskell
./node_modules/.bin/surql-gen --no-generateClient
No config file found.
Starting temporary SurrealDB instance
Temporary SurrealDB instance started at http://localhost:33789
Connecting to database
Connected to database successfully

🔴 This did not work as expected 🥺
🔴 I am sorry that this happened, and I kindly ask for your help to fix this.
🔴
🔴 Please open an issue here:
🔴 👉 https://github.com/sebastianwessel/surrealdb-client-generator/issues
🔴
🔴 Please copy & paste the following code into the ticket:
=====
ResponseError: There was a problem with the database: Parse error: Failed to parse query at line 109 column 61 expected function arguments
    |
109 | ...ice(record::id($value.id), 0, 4);
    |              ^

    at Surreal.query_raw (/node_modules/.pnpm/surrealdb@1.0.0-beta.21_tslib@2.7.0_typescript@5.6.2_ws@8.18.0_bufferutil@4.0.8_utf-8-validate@6.0.4_/node_modules/surrealdb/dist/index.cjs:1:45589)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Surreal.query (/node_modules/.pnpm/surrealdb@1.0.0-beta.21_tslib@2.7.0_typescript@5.6.2_ws@8.18.0_bufferutil@4.0.8_utf-8-validate@6.0.4_/node_modules/surrealdb/dist/index.cjs:1:45244)
    at async insertDefinitions (/node_modules/.pnpm/@sebastianwessel+surql-gen@2.6.1_tslib@2.7.0_typescript@5.6.2_ws@8.18.0_bufferutil@4.0.8_utf-8-validate@6.0.4_/node_modules/@sebastianwessel/surql-gen/dist/index.js:92:3)
    at async main (/node_modules/.pnpm/@sebastianwessel+surql-gen@2.6.1_tslib@2.7.0_typescript@5.6.2_ws@8.18.0_bufferutil@4.0.8_utf-8-validate@6.0.4_/node_modules/@sebastianwessel/surql-gen/dist/index.js:1006:9)
```

**Comment by sebastianwessel** [comment]
From first guess, looks like an issue in the surrealdb (client)

**Comment by hammo92** [comment]
@zvictor did you provide a schema file?

**Comment by zvictor** [comment]
of course. the `record::id` is part of the schema. Once I get back to my computer I will reply with an example schema

**Comment by hammo92** [comment]
> of course. the `record::id` is part of the schema. Once I get back to my computer I will reply with an example schema

Okay, try adding the `-i` flag with the nightly image `surrealdb/surrealdb:nightly` see if that fixes the issue for you.

**Comment by zvictor** [comment]
That works! I am sorry I didn't notice the `--surrealImage` had been added...

Morever, to my surprise, using `--surrealImage surrealdb/surrealdb:nightly` also gets rid of #63.
